#!/bin/sh

##  DESCRIPTION
##  This script checks if crontab has been modified and sends an email to root.

if [ "$(md5sum -c /etc/crontab)" != "$(cat /var/log/watch_crontab.log)" ]
then
	echo "/etc/crontab was changed !" | mail -s "Crontab has been modified !" root
	md5sum /etc/crontab > /var/log/watch_crontab.log
fi
